
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '*.*/*.csproj'
    feedsToUse: 'select'


- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*.*/*.csproj'



- task: Npm@1
  inputs:
    command: 'install'
    workingDir: 'Clientapp'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'Clientapp'
    customCommand: 'run build'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist'
    ArtifactName: 'drop'
    publishLocation: 'Container'